### ISSUE TITLE
能否适配一下 Android 12？

### ISSUE THREAD

**Issue by iKangnakamuyi** [yanbuyu/XiaomiCTSPass#16]

**Comment by yanbuyu** [comment]
需要等官方更新稳定版，估计要等到MIUI13正式推送了

**Comment by yanbuyu** [comment]
> > 需要等官方更新稳定版，估计要等到MIUI13正式推送了
> 
> 能不能先给推送了 12 稳定版的先弄呢，比如 MIX4 和小米 11 系

已经支持安卓12，对于无安卓12稳定版的机型，已正式开启兼容模式，自测能过CTS检测。

**Comment by xayane** [comment]
![IMG_20220211_183729](https://user-images.githubusercontent.com/9472580/153577224-e399f33b-a0a5-4ff5-963e-588dc0c1b5a1.jpg)
小米11pro，开发板，刷了universal safetynet fix 2.2.1和xiaomictspass 1.4.3。没过cts，我看了一下，指纹好像有点问题，我应该是mars，但是显示改成了star。

**Comment by yanbuyu** [comment]
> 

这个应该影响不大，我小米10都是用小米12的指纹过CTS的，你去下个YASNAC，挂梯子测一下。

**Comment by iKangnakamuyi** [comment]
> > 
> 
> 这个应该影响不大，我小米10都是用小米12的指纹过CTS的，你去下个YASNAC，挂梯子测一下。

![Screenshot_2022-02-12-16-19-27-565_rikka safetynetchecker](https://user-images.githubusercontent.com/47733293/153703424-3990912a-e232-44db-9105-2f9ab80701ae.jpg)

然而我这台 Mi 11 Ultra 并不能通过认证

**Comment by TigerBeanst** [comment]
![Screenshot_2022-02-15-12-13-40-483_rikka safetynetchecker](https://user-images.githubusercontent.com/3889846/153991480-1f09d1a8-59c4-4e1b-acf5-17b2bf0a584e.jpg)
![Screenshot_2022-02-15-12-13-53-645_vwes hv](https://user-images.githubusercontent.com/3889846/153991494-df95874c-c9ee-415d-8b0d-58d49b711c71.jpg)
同样，配合两个模块无法过CTS。
是否仍需要XprivacyLua？

**Comment by yanbuyu** [comment]
这是我安卓12提取指纹出现了问题，后面的版本应该已修复这个问题。
