### ISSUE TITLE
模块内安卓12的k40指纹疑似有误

### ISSUE THREAD

**Issue by Daxiaha** [yanbuyu/XiaomiCTSPass#22]
ro.build.fingerprint=Redmi/alioth/alioth:12/SKQ1.211006.001/V13.0.3.0.SKHCNXM:user/release-keys
ro.build.description=alioth-user 12 SKQ1.211006.001 V13.0.3.0.SKHCNXM release-keys
ro.build.version.security_patch=2021-12-01

正确指纹应该是这个，供作者参考

**Comment by MoeBai** [comment]
我也发现了这个问题，准备来提issue，发现有人给解决方案了，我还以为是稳定版内测指纹用不了。

**Comment by yanbuyu** [comment]
> > 我也发现了这个问题，准备来提issue，发现有人给解决方案了，我还以为是稳定版内测指纹用不了。
> 
> 我是在1.3.0版本的时候就找到了这个指纹，作者更新后我也好奇拆包看了下发现不一样，后来刷入也发现过不了，于是就提交issue上去了

感谢，待会提交到仓库。

**Comment by yanbuyu** [comment]
SKQ1.211006.001这个是小米12机型的，我拆包看，k40应该是RKQ1.200826.002

**Comment by MoeBai** [comment]
话说稳定版内测的指纹能过safetynet吗

**Comment by yanbuyu** [comment]
> 话说稳定版内测的指纹能过safetynet吗

灰度内测需要等吧，之前mi10用灰度内测，一开始过不了，后来等几天就过了，我估计要等灰度内测转为公测。

**Comment by MoeBai** [comment]
好的,感谢大佬解答

**Comment by Daxiaha** [comment]
> SKQ1.211006.001这个是小米12机型的，我拆包看，k40应该是RKQ1.200826.002

该指纹是我从酷安momo评论区一位k40用户发送的截图中获得的，按理说是k40的没错，但也不排除他也更改了自己的指纹，但看着不像

**Comment by Daxiaha** [comment]
> SKQ1.211006.001这个是小米12机型的，我拆包看，k40应该是RKQ1.200826.002

我个人觉得指纹只与版本号有关，与机型无关🤔

**Comment by yanbuyu** [comment]
> > SKQ1.211006.001这个是小米12机型的，我拆包看，k40应该是RKQ1.200826.002
> 
> 我个人觉得指纹那段只与版本号有关，与机型无关🤔

知道原因了，出厂不是安卓11的设备，升级安卓12后vendor不是安卓12的底层，而是安卓11的底层，因此是RKQ开头。因此，我提取时不能直接复制vendor里的指纹，而是要复制vendor指纹后替换成安卓12的ro.system.build.id

**Comment by yanbuyu** [comment]
感谢你的反馈，待会修复安卓12不能过cts检测的bug
