### ISSUE TITLE
自定義部份要支援其他牌子的手機可能嗎？

### ISSUE THREAD

**Issue by skysumbra** [yanbuyu/XiaomiCTSPass#3]
如果在資料夾props 下新增一份新的

ro.build.fingerprint=
ro.build.description=
ro.build.version.security_patch=

其內容找一台有支援的手機，然後寫一樣的值可以嗎？
如果可以此方式新增，腳本還要改哪裡呢？

**Comment by yanbuyu** [comment]
脚本不需要改，只要修改props下相关文件名字，下划线前面的机型号要与你的手机代号相匹配

**Comment by skysumbra** [comment]
那/props 下藥新增的檔案名稱要寫什麼呢？？   ---> ???_sdk??.prop    ???的部份
希望目前有的不要修改到

**Comment by yanbuyu** [comment]
如果手机有终端的话输入getprop ro.product.device获取机型代号，输入getprop ro.build.version.sdk获取SDK版本号，然后把这两个值填入xxx_sdkxxx.prop.
