### ISSUE TITLE
Redmi NOTE9	5G (cannon) failed

### ISSUE THREAD

**Issue by weijen6** [yanbuyu/XiaomiCTSPass#4]
Hello, My environment
Magisk 23.0
- Busybox for Android SDK
- Universal SafetyNet Fix
- Weeb GApps on Android R
- Xiaomi CTS Pass
- Xiaomi CTS Pass檢測模塊
MIUI 12.5.1
![image](https://user-images.githubusercontent.com/32688959/120441815-899aff00-c3b7-11eb-88c2-651e41f01e59.png)

**Comment by yanbuyu** [comment]
- 1.你尝试用SafetyNet Test应用检测（谷歌商店有下。
- 2.若在中国大陆，可能需要绕过GFW再检测。
- 3.MIUI稳定版可以通过谷歌CTS检测，无需安装XiaomiCTSPass模块（此模块就是模拟MIUI稳定版环境）。

**Comment by LeviMarvin** [comment]
我的note 9 5g（cannon）是可以正常通过的虽然伪装机型是alioth
