### ISSUE TITLE
提供 小米 Pad 6 Pro WiFi (liuqin) v14.0.5 指纹

### ISSUE THREAD

**Issue by AllsVoid** [yanbuyu/XiaomiCTSPass#70]
`ro.build.fingerprint=Xiaomi/liuqin/liuqin:13/TKQ1.221114.001/V14.0.5.0.TMYCNXM:user/release-keys`
`ro.build.description=liuqin-user 13 TKQ1.221114.001 V14.0.5.0.TMYCNXM release-keys`
`ro.build.version.security_patch=2023-05-01`

**Comment by dee-lii** [comment]
老哥方便问下这个是怎么提取的吗

**Comment by AllsVoid** [comment]
设备接在电脑上，使用 `adb shell get <ro.build.xxx>` 就可以了

**Comment by dee-lii** [comment]
然后怎么用啊我提取出来了，求教

**Comment by dee-lii** [comment]
ro.build.fingerprint=Xiaomi/yudi/yudi:13/TKQ1.221114.001/V14.0.3.0.TMHCNXM:user/release-keys
ro.build.description=yudi-user 13 TKQ1.221114.001 V14.0.3.0.TMHCNXM release-keys
ro.build.version.security_patch=2023-07-01


老哥我提取了指纹也按照文件填了刷进去还是没过，我的是小米平板6max 14.0.3.0稳定版

**Comment by AllsVoid** [comment]
https://github.com/yanbuyu/XiaomiCTSPass#%E7%89%B9%E5%88%AB%E8%AF%B4%E6%98%8E
刷进去后需要重启两次才能生效，没有的话换成 [Safetynet-fix](https://github.com/Displax/safetynet-fix) 试试看

**Comment by xiaoBingge114514** [comment]
![image](https://github.com/yanbuyu/XiaomiCTSPass/assets/105868119/4d7c0c6d-83c1-4a72-ac7f-a0794a801d3e)
这个怎么办

**Comment by AllsVoid** [comment]
> 

不需要加 `<>`，这个只是用来提示的
